# ansible/roles/git-clone/tasks/main.yml
---
- name: Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone homelab-docker repo
  git:
    repo: "{{ homelab_repo }}"
    dest: "{{ homelab_dest }}"
    version: "{{ homelab_version }}"
    force: yes
    update: yes
  when: ansible_connection != 'local'

- name: Ensure ownership on the repo folder (skip in devcontainer to avoid permission errors)
  file:
    path: "{{ homelab_dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  when: ansible_connection != "local"