# docker-compose.override.yml
services:
  adguardhome:
    ports:
      - "${adguard_ui_port:-3010}:80/tcp"
      - "${adguard_dns_port:-53}:53/udp"
      - "${adguard_dns_port:-53}:53/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/adguardhome/work:/opt/adguardhome/work:rw"
      - "${HOMELAB_DOCKER_PATH}/adguardhome/conf:/opt/adguardhome/conf:rw"

  netdata:
    ports:
      - "${netdata_port:-19999}:19999"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/netdata/netdataconfig:/etc/netdata:rw"
      - "${HOMELAB_DOCKER_PATH}/netdata/netdatalib:/var/lib/netdata:rw"
      - "${HOMELAB_DOCKER_PATH}/netdata/netdatacache:/var/cache/netdata:rw"

  glances:
    ports:
      - "${glances_port:-61208}:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"

  homepage:
    ports:
      - "${homepage_port:-3020}:3000/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/homepage/config:/app/config:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - HOMEPAGE_VAR_ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}

  uptime-kuma:
    ports:
      - "${uptime_kuma_port:-3001}:3001/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/uptime-kuma/data:/app/data:rw"

  openspeedtest:
    ports:
      - "${openspeedtest_port:-3003}:3000/tcp"

  wireguard:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN 
    security_opt:
      - "apparmor:unconfined"
    restart: unless-stopped
    # For network_mode: host, this port mapping is informational; 
    # the container listens on wireguard_int_port directly on the host.
    ports:
      - "${wireguard_ext_port:-45000}:${wireguard_int_port:-51820}/udp" 
    volumes:
      - "${HOMELAB_DOCKER_PATH}/wireguard/config:/config:rw"
      - "/lib/modules:/lib/modules:ro"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}
      - SERVERURL=${WIREGUARD_SERVERURL:-vpn.vidafora.com}
      - SERVERPORT=${wireguard_ext_port:-45000} # Clients connect to this external port
      - PEERS=${wireguard_peers:-1} # Using the variable from host_vars
      - PEERDNS=${wireguard_peerdns:-10.13.13.1}
      - INTERNAL_SUBNET=${WIREGUARD_INTERNAL_SUBNET:-10.13.13.0/24}
      - ALLOWEDIPS=0.0.0.0/0, ::/0
      - WG_CONF_DIR=wg_confs # ADDED: To specify the config subdirectory
      # - LOG_CONFS=true

  homeassistant:
    ports:
      - "${home_assistant_port:-8123}:8123/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/homeassistant/config:/config:rw"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  qbittorrent:
    ports:
      - "${qbittorrent_port:-8080}:8080"
      - "${qbittorrent_tcp_port:-6881}:${qbittorrent_tcp_port:-6881}"
      - "${qbittorrent_udp_port:-6881}:${qbittorrent_udp_port:-6881}/udp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/qbittorrent/config:/config"
      - "${HOMELAB_DOCKER_PATH}/media/downloads:/downloads"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}
      - WEBUI_PORT=${qbittorrent_port:-8080}

  sonarr:
    ports:
      - "${sonarr_port:-8989}:8989"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/sonarr/config:/config"
      - "${HOMELAB_DOCKER_PATH}/media/tv:/tv"
      - "${HOMELAB_DOCKER_PATH}/media/downloads:/downloads"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  radarr:
    ports:
      - "${radarr_port:-7878}:7878"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/radarr/config:/config"
      - "${HOMELAB_DOCKER_PATH}/media/movies:/movies"
      - "${HOMELAB_DOCKER_PATH}/media/downloads:/downloads"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  lidarr:
    ports:
      - "${lidarr_port:-8686}:8686"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/lidarr/config:/config"
      - "${HOMELAB_DOCKER_PATH}/media/music:/music"
      - "${HOMELAB_DOCKER_PATH}/media/downloads:/downloads"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  bazarr:
    ports:
      - "${bazarr_port:-6767}:6767"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/bazarr/config:/config"
      - "${HOMELAB_DOCKER_PATH}/media/movies:/movies"
      - "${HOMELAB_DOCKER_PATH}/media/tv:/tv"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  jellyseerr:
    ports:
      - "${jellyseerr_port:-5055}:5055"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/jellyseerr/config:/app/config"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  jellyfin:
    ports:
      - "${jellyfin_port:-8096}:8096"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/jellyfin/config:/config"
      - "${HOMELAB_DOCKER_PATH}/media/tv:/data/tvshows"
      - "${HOMELAB_DOCKER_PATH}/media/movies:/data/movies"
      - "${HOMELAB_DOCKER_PATH}/media/music:/data/music"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}

  prowlarr:
    ports:
      - "${prowlarr_port:-9696}:9696"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/prowlarr/config:/config"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}