# docker-compose.override.yml
services:
  adguardhome:
    ports:
      - "${adguard_ui_port:-3010}:80/tcp"
      - "${adguard_dns_port:-53}:53/udp"
      - "${adguard_dns_port:-53}:53/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/adguardhome/work:/opt/adguardhome/work:rw"
      - "${HOMELAB_DOCKER_PATH}/adguardhome/conf:/opt/adguardhome/conf:rw"

  netdata:
    ports:
      - "${netdata_port:-19999}:19999"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/netdata/netdataconfig:/etc/netdata:rw"
      - "${HOMELAB_DOCKER_PATH}/netdata/netdatalib:/var/lib/netdata:rw"
      - "${HOMELAB_DOCKER_PATH}/netdata/netdatacache:/var/cache/netdata:rw"

  glances:
    ports:
      - "${glances_port:-61208}:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"

  homepage:
    ports:
      - "${homepage_port:-3020}:3000/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/homepage/config:/app/config:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - HOMEPAGE_VAR_ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}

  uptime-kuma:
    ports:
      - "${uptime_kuma_port:-3001}:3001/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/uptime-kuma/data:/app/data:rw"

  openspeedtest:
    ports:
      - "${openspeedtest_port:-3003}:3000/tcp"

  wireguard:
    network_mode: host
    cap_add:
      - NET_ADMIN
    security_opt:
      - "apparmor:unconfined"
    restart: unless-stopped
    ports:
      - "${wireguard_port:-45000}:51820/udp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/wireguard/config:/config:rw"
      - "/lib/modules:/lib/modules:ro"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Lisbon}
      - SERVERURL=${WIREGUARD_SERVERURL:-vpn.vidafora.com}
      - SERVERPORT=${wireguard_port:-45000}
      # - PEERS=2
      - PEERS="phone" # "phone,laptop"
      - PEERDNS=off
      - INTERNAL_SUBNET=${WIREGUARD_INTERNAL_SUBNET:-10.13.13.0/24}
      - ALLOWEDIPS=0.0.0.0/0, ::/0
      - WG_CONF_DIR=wg_confs # ADDED: To specify the config subdirectory
      # - LOG_CONFS=true