# docker-compose.yml - Umbrella for Homelab Docker Services

services:
  # pihole:
  #   extends:
  #     file: ./pihole/docker-compose.yml
  #     service: pihole
  #   # volumes:
  #   #   - homelab_data:/data/shared

  adguardhome:
    extends:
      file: ./adguardhome/docker-compose.yml
      service: adguardhome
      # volumes:
      #   - adguard_data:/opt/adguardhome/work
      #   - adguard_config:/opt/adguardhome/conf

  netdata:
    extends:
      file: ./netdata/docker-compose.yml
      service: netdata

  glances:
    extends:
      file: ./glances/docker-compose.yml
      service: glances

  homepage:
    extends:
      file: ./homepage/docker-compose.yml
      service: homepage

  uptime-kuma:
    extends:
      file: ./uptime-kuma/docker-compose.yml
      service: uptime-kuma

  openspeedtest:
    extends:
      file: ./openspeedtest/docker-compose.yml
      service: openspeedtest

  # dashy:
  #   extends:
  #     file: ./dashy/docker-compose.yml
  #     service: dashy



volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  adguard_data:
  adguard_config:
