# docker-compose.override.yml
services:
  adguardhome:
    ports:
      - "${adguard_ui_port:-3010}:80/tcp"
      - "${adguard_dns_port:-53}:53/udp"
      - "${adguard_dns_port:-53}:53/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/adguardhome/work:/opt/adguardhome/work:rw"
      - "${HOMELAB_DOCKER_PATH}/adguardhome/conf:/opt/adguardhome/conf:rw"

  netdata:
    ports:
      - "${netdata_port:-19999}:19999"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/netdata/netdataconfig:/etc/netdata:rw"
      - "${HOMELAB_DOCKER_PATH}/netdata/netdatalib:/var/lib/netdata:rw"
      - "${HOMELAB_DOCKER_PATH}/netdata/netdatacache:/var/cache/netdata:rw"

  glances:
    ports:
      - "${glances_port:-61208}:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"

  homepage:
    ports:
      - "${homepage_port:-3020}:3000/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/homepage/config:/app/config:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - HOMEPAGE_VAR_ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}

  uptime-kuma:
    ports:
      - "${uptime_kuma_port:-3001}:3001/tcp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/uptime-kuma/data:/app/data:rw"

  openspeedtest:
    ports:
      - "${openspeedtest_port:-3003}:3000/tcp"

  wireguard:
    ports:
      # The host port (left side) uses wireguard_port (45000)
      # The container port (right side) is WireGuard's internal listening port (51820)
      - "${wireguard_port:-45000}:51820/udp"
    volumes:
      - "${HOMELAB_DOCKER_PATH}/wireguard/config:/config:rw"
      - "/lib/modules:/lib/modules:ro" # If kernel headers are needed
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - SERVERURL=${wireguard_server_url:-auto} # This will be vpn.vidafora.com on server
      - SERVERPORT=${wireguard_port:-45000}    # CRITICAL: This tells WireGuard client configs to use port 45000
      - PEERS=${wireguard_peers:-1}             # e.g., phone,laptop
      - PEERDNS=${wireguard_peerdns:-auto}      # Or your AdGuard Home Docker IP
      - INTERNAL_SUBNET=${wireguard_internal_subnet:-10.13.13.0/24}
      # - ALLOWEDIPS=0.0.0.0/0, ::/0 # For full tunnel.
      # - LOG_CONFS=true