version: '2.4'

# volumes:
#   homelab_data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /home/gabriel/homelab-data   # host dir for all shared data

services:
  pihole:
    extends:
      file: ./pihole/docker-compose.yml
      service: pihole
    # volumes:
    #   - homelab_data:/data/shared

  netdata:
    extends:
      file: ./netdata/docker-compose.yml
      service: netdata

  glances:
    extends:
      file: ./glances/docker-compose.yml
      service: glances

  homepage:
    extends:
      file: ./homepage/docker-compose.yml
      service: homepage

  dashy:
    extends:
      file: ./dashy/docker-compose.yml
      service: dashy