# version: '2.4'

services:
  pihole:
    extends:
      file: ./pihole/docker-compose.yml
      service: pihole
    # volumes:
    #   - homelab_data:/data/shared

  netdata:
    extends:
      file: ./netdata/docker-compose.yml
      service: netdata

  glances:
    extends:
      file: ./glances/docker-compose.yml
      service: glances

  homepage:
    extends:
      file: ./homepage/docker-compose.yml
      service: homepage

  dashy:
    extends:
      file: ./dashy/docker-compose.yml
      service: dashy



volumes:
#   homelab_data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /home/gabriel/homelab-data   # host dir for all shared data
  # Netdata named volumes
  netdataconfig:
  netdatalib:
  netdatacache:

  # If you have other named volumes, declare them here too:
  # dashy_data:
  # pihole_data: