# docker-compose.override.yml
services:
  pihole:
    volumes:
      - "/Users/gabriel/dev/homelab-docker/pihole/etc-pihole:/etc/pihole:rw"
      - "/Users/gabriel/dev/homelab-docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw"

  netdata:
    ports:
      - "19998:19999"
    volumes:
      - "/Users/gabriel/dev/homelab-docker/netdata/netdataconfig:/etc/netdata:rw"
      - "/Users/gabriel/dev/homelab-docker/netdata/netdatalib:/var/lib/netdata:rw"
      - "/Users/gabriel/dev/homelab-docker/netdata/netdatacache:/var/cache/netdata:rw"

  glances:
    ports:
      - "61209:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"

  homepage:
    ports:
      - "3001:3001"
    volumes:
      - "/Users/gabriel/dev/homelab-docker/homepage/config:/app/config:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  dashy:
    ports:
      - "4001:8080"
    volumes:
      - "/Users/gabriel/dev/homelab-docker/dashy/conf.yml:/app/user-data/conf.yml:ro"
      - "/Users/gabriel/dev/homelab-docker/dashy/data/glances-widgets.yml:/app/user-data/glances-widgets.yml:ro"