# ansdible/inventory/hosts.yml
all:
  children:
    homelab:
      hosts:
        homelab-server:
          ansible_host: 192.168.1.92
          ansible_user: gabriel
          ansible_become: true
          # ansible_ssh_private_key_file: /path/to/key    # if using key auth
        localhost:
          ansible_connection: local
          ansible_user: vscode      # your local username in the devcontainer
          ansible_become: true