version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: 'your-password'   # change this!
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN  # required to bind to DNS ports
