version: '3.8'

volumes:
  homelab-docker:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      # mount the exact config subfolder from your repo:
      - homelab-docker:/home/gabriel/dev/homelab-docker/homepage/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homelab:3000,192.168.1.92:3000
    restart: unless-stopped