
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      # Bind your Git checkout config directory directly
      - /home/gabriel/dev/homelab-docker/homepage/config:/app/config:ro
      # Optional: Docker socket for service discovery/widgets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Allow access by hostname or IP
      HOMEPAGE_ALLOWED_HOSTS: homelab:3000,192.168.1.92:3000
    restart: unless-stopped