services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      # Bind exactly the config folder from your homelab-docker volume:
      - type: bind
        source: /var/lib/docker/volumes/homelab-docker/_data/homepage/config
        target: /app/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homelab:3000,192.168.1.92:3000
    restart: unless-stopped