version: '3.8'

services:
  homepage:
    image: homepage-dev/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      # Optional: mount in a custom config file if you want to tweak the homepage
      - ./config.yml:/app/config.yml
    restart: unless-stopped
