version: '3.8'

services:
  homepage:
    # Use the public GHCR image, not homepage-dev/homepage
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - /path/to/config:/app/config
      # - ./config:/app/config:ro
      # - type: bind
      #   source: /var/lib/docker/volumes/portainer_data/_data/compose/14/homepage/config
      #   target: /app/config:ro
      # - type: bind
      #   source: /var/run/docker.sock
      #   target: /var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homelab:3000
      # - PUID: 1000
      # - PGID: 1000
    restart: unless-stopped