services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      # Relative bind: the 'config' folder next to this compose file
      - ./config:/app/config:ro

      # Docker socket (if you need it)
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      HOMEPAGE_ALLOWED_HOSTS: homelab:3000,192.168.1.92:3000
    restart: unless-stopped