# ansible/roles/ufw/tasks/main.yml
---
- block:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Ensure UFW is enabled
      community.general.ufw:
        state: enabled
        policy: deny # Deny incoming by default

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        name: OpenSSH # Using the application profile
        comment: "Allow SSH connections"

    - name: Allow Homepage dashboard
      community.general.ufw:
        rule: allow
        port: "{{ homepage_port }}"
        proto: tcp
        comment: "Allow Homepage dashboard UI (Port {{ homepage_port }})"
      when: homepage_port is defined

    - name: Allow Glances system monitor
      community.general.ufw:
        rule: allow
        port: "{{ glances_port }}"
        proto: tcp
        comment: "Allow Glances system monitor UI (Port {{ glances_port }})"
      when: glances_port is defined

    - name: Allow Netdata monitor
      community.general.ufw:
        rule: allow
        port: "{{ netdata_port }}"
        proto: tcp
        comment: "Allow Netdata real-time monitor UI (Port {{ netdata_port }})"
      when: netdata_port is defined

    - name: Allow Portainer
      community.general.ufw:
        rule: allow
        port: "{{ portainer_port | default('9000') }}"
        proto: tcp
        comment: "Allow Portainer UI (Port {{ portainer_port | default('9000') }})"
      when: portainer_port is defined or true # Assuming Portainer is always deployed or has a default

    - name: Allow AdGuard Home DNS (TCP)
      community.general.ufw:
        rule: allow
        port: "{{ adguard_dns_port }}"
        proto: tcp
        comment: "Allow AdGuard Home DNS (TCP Port {{ adguard_dns_port }})"
      when: adguard_dns_port is defined

    - name: Allow AdGuard Home DNS (UDP)
      community.general.ufw:
        rule: allow
        port: "{{ adguard_dns_port }}"
        proto: udp
        comment: "Allow AdGuard Home DNS (UDP Port {{ adguard_dns_port }})"
      when: adguard_dns_port is defined

    - name: Allow AdGuard Home Web UI
      community.general.ufw:
        rule: allow
        port: "{{ adguard_ui_port }}"
        proto: tcp
        comment: "Allow AdGuard Home Web UI (Port {{ adguard_ui_port }})"
      when: adguard_ui_port is defined

    - name: Allow Uptime Kuma UI
      community.general.ufw:
        rule: allow
        port: "{{ uptime_kuma_port }}"
        proto: tcp
        comment: "Allow Uptime Kuma monitoring UI (Port {{ uptime_kuma_port }})"
      when: uptime_kuma_port is defined

    - name: Allow OpenSpeedTest UI
      community.general.ufw:
        rule: allow
        port: "{{ openspeedtest_port }}"
        proto: tcp
        comment: "Allow OpenSpeedTest UI (Port {{ openspeedtest_port }})"
      when: openspeedtest_port is defined

    - name: Allow WireGuard (UDP)
      community.general.ufw:
        rule: allow
        port: "{{ wireguard_int_port }}" # UFW opens the internal host listening port
        proto: udp
        comment: "Allow WireGuard VPN (UDP Port {{ wireguard_int_port }} - Host Listen Port)"
      when: wireguard_int_port is defined

  become: yes
  when: ansible_connection != "local"