version: '3.8'

services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    restart: unless-stopped