---
# config/bookmarks.yml
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks/

- Core Services:
    - Dashy:
        - abbr: DS
          href: http://192.168.1.92:4000
          icon: dashy.png
    - Portainer:
        - abbr: PT
          href: http://192.168.1.92:9000
          icon: portainer.png

- Network & Monitoring:
    - AdGuard-Home:
        - abbr: AG
          href: http://192.168.1.92:3010
          icon: adguard-home.png
    - Pi-hole:
        - abbr: PH
          href: http://192.168.1.92/admin
          icon: pi-hole.png
    - Netdata:
        - abbr: ND
          href: http://192.168.1.92:19999
          icon: netdata.png
    - Glances:
        - abbr: GL
          href: http://192.168.1.92:61208
          icon: glances.png
    - OpenSpeedTest:
        - abbr: OST
          href: http://192.168.1.92:3003

- Self:
    - Homepage.dev:
        - abbr: HP
          href: http://192.168.1.92:3010
          icon: homepage.png

- Documentation:
    - Homepage:
        - abbr: HP
          href: https://gethomepage.dev/
          icon: homepage.png
    - Ansible:
        - abbr: AN
          href: https://docs.ansible.com/
          icon: ansible.png
    - Docker:
        - abbr: DC
          href: https://docs.docker.com/
          icon: docker.png

- Media:
    - TRaSH Guides:
        - abbr: TG
          href: https://trash-guides.info/
          icon: trash-guides.png
    - Prowlarr:
        - abbr: PR
          href: http://192.168.1.92:9696
          icon: prowlarr.png