# config/config.yml

# General Settings
title: "🏠 Homelab Homepage"
description: "Quick links & widgets for my Homelab"

# Links section
links:
  - name: "Dashy"
    url: http://homelab:4000
    icon: dashboard
  - name: "Homepage.dev"
    url: http://homelab:3000
    icon: home
  - name: "Portainer"
    url: http://homelab:9000
    icon: dashboard_customize
  - name: "Pi-hole"
    url: http://homelab/admin
    icon: block
  - name: "Netdata"
    url: http://homelab:19999
    icon: speed

# Widgets (Glances system monitoring)
widgets:
  - type: glances.cpu              # CPU chart
    server: local                 # name of the Docker server
    container: glances            # container name (optional for system-wide)
    title: "CPU Usage"
    size: small
  - type: glances.mem             # Memory gauge
    title: "Memory"
    size: small
  - type: glances.disk            # Disk usage
    title: "Disk"
    mountpoint: "/"               # root filesystem
    size: small
  - type: glances.alerts          # Alerts widget
    title: "Glances Alerts"
    size: medium