---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/


- Home Automation:
    - Home Assistant:
        description: Home automation platform
        href: http://192.168.1.92:8123 # Using the default Home Assistant port
        icon: mdi-home-assistant # Material Design Icon for Home Assistant
        
        siteMonitor: http://192.168.1.92:8123

- Homelab Status:
    - Uptime Kuma:
        description: Monitoring and status page for your homelab
        href: http://192.168.1.92:3001
        icon: uptime-kuma
        siteMonitor: http://192.168.1.92:3001

- Homelab Tools:
    - Glances:
        href: http://192.168.1.92:61208
        description: Simple resource usage via Glances
        icon: glances.png
        siteMonitor: http://192.168.1.92:61208
    - Portainer:
        href: http://192.168.1.92:9000
        description: Docker management via Portainer
        icon: portainer.png
        siteMonitor: http://192.168.1.92:9000
        widget:
          type: portainer
          url: http://192.168.1.92:9000
          env: 1
          key: ptr_dLe4S8alpp8iEBLZ6oaUnf7P6kraPa0nHxu0fV2Pijw=