---
# config/widgets.yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    alerts: true


# - My Homelab Status: # This is the group title that will appear on Homepage
#     - Uptime Kuma:
#         widget:
#         type: uptimekuma
#         url: http://192.168.1.92:3001  # Base URL of your Uptime Kuma instance
#         slug: homelab-status          # The slug of the status page you created in Uptime Kuma
#         # Optional parameters (refer to Homepage documentation for more):
#         # title: "Live Service Status" # Override the title from Uptime Kuma for the widget
#         # columns: 3                   # Number of columns for monitors display
#         # showTags: true               # If you want to display tags from Uptime Kuma
#         # hideDownMonitors: false      # Set to true if you want to hide monitors that are down

# - adguard:
#     url: http://adguardhome:80
#     username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
#     password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"

- search:
    provider: duckduckgo
    target: _blank

- qbittorrent:
    url: http://192.168.1.92:8080

- sonarr:
    url: http://192.168.1.92:8989
    apiKey: {{HOMEPAGE_VAR_SONARR_API_KEY}}

- radarr:
    url: http://192.168.1.92:7878
    apiKey: {{HOMEPAGE_VAR_RADARR_API_KEY}}

- lidarr:
    url: http://192.168.1.92:8686
    apiKey: {{HOMEPAGE_VAR_LIDARR_API_KEY}}