---
# config/widgets.yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets/

# - My Homelab Status: # This is the group title that will appear on Homepage
#     - Uptime Kuma:
#         widget:
#         type: uptimekuma
#         url: http://192.168.1.92:3001  # Base URL of your Uptime Kuma instance
#         slug: homelab-status          # The slug of the status page you created in Uptime Kuma
#         # Optional parameters (refer to Homepage documentation for more):
#         # title: "Live Service Status" # Override the title from Uptime Kuma for the widget
#         # columns: 3                   # Number of columns for monitors display
#         # showTags: true               # If you want to display tags from Uptime Kuma
#         # hideDownMonitors: false      # Set to true if you want to hide monitors that are down

# - adguard:
#     url: http://adguardhome:80
#     username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
#     password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"

- resources:
    label: System
    cpu: true
    memory: true
    disk: /
    
- datetime:
    text_size: xl
    format:
      timeStyle: long
      dateStyle: full

- search:
    provider: duckduckgo
    target: _blank

- group:
    - name: "*Arr Stack"
      columns: 2
      widgets:
        - sonarr:
            url: http://192.168.1.92:8989
            apiKey: {{HOMEPAGE_VAR_SONARR_API_KEY}}
        - radarr:
            url: http://192.168.1.92:7878
            apiKey: {{HOMEPAGE_VAR_RADARR_API_KEY}}
        - lidarr:
            url: http://192.168.1.92:8686
            apiKey: {{HOMEPAGE_VAR_LIDARR_API_KEY}}
        - prowlarr:
            url: http://192.168.1.92:9696
            apiKey: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

- group:
    - name: Downloads
      columns: 1
      widgets:
        - qbittorrent:
            url: http://192.168.1.92:8080

- group:
    - name: Monitoring
      columns: 2
      widgets:
        - glances:
            url: http://192.168.1.92:61208
            expanded: true
        - netdata:
            url: http://192.168.1.92:19999
            
- adguard:
    url: http://192.168.1.92:3010
    username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
    password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}