version: '3.8'

services:
  dashy:
    image: ghcr.io/lissy93/dashy:latest
    container_name: dashy
    ports:
      - 4000:8080
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
