version: '3.8'

services:
  dashy:
    image: ghcr.io/lissy93/dashy:latest
    container_name: dashy
    ports:
      - 4000:80
    volumes:
      - ./conf.yml:/app/public/conf.yml
    restart: unless-stopped
