services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE # Required for kernel module operations
    security_opt: # ADDED
      - "apparmor:unconfined" # ADDED
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      # Add if you want IPv6 support in the tunnel
      # - net.ipv6.conf.all.disable_ipv6=0
      # - net.ipv6.conf.default.disable_ipv6=0
      # - net.ipv6.conf.lo.disable_ipv6=0
    restart: unless-stopped
    # Ports, volumes, and environment variables will be defined in the override file