services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    network_mode: host
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE # Required for kernel module operations
    security_opt:
      - "apparmor:unconfined"
    restart: unless-stopped
    # Ports, volumes, and environment variables will be defined in the override file