# wireguard/docker-compose.yml
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    network_mode: host  
    restart: unless-stopped
    # Ports, volumes, and environment variables will be defined in the override file